---
- name: test when_set
  hosts: localhost

  vars:
    - set: a set var

  tasks:
    - name: when_set $ set
      command: /bin/true
      when_set: $set
    
    - name: when_set $ unset
      command: /bin/true
      when_set: $unset
    
    - name: when_set $ unset and not $ set
      command: /bin/true
      when_set: $unset and not $set
    
    - name: when_set $ unset or $ set
      command: /bin/true
      when_set: $unset or $set
    
    - name: when_set and thing in list or otherthing in list
      command: bin/true
      when: "subs is defined and \"'thing' in list or 'otherthing' in list\""
